variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true
  FF_NETWORK_PER_BUILD: "true"


image: maven:latest

cache:
  paths:
    - .m2/repository


stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - docker-runner
  services:
    - name: confluentinc/cp-zookeeper:7.5.2
      alias: zookeeper
      variables:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    - name: confluentinc/cp-kafka:7.5.2
      alias: kafka
      variables:
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,EXTERNAL://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    - name: confluentinc/cp-kafka:7.5.2
      alias: init-kafka
      command: ["sh", "-c", "'echo Waiting for Kafka to be ready... && \
      kafka-topics --bootstrap-server kafka:19092 --list && \
      kafka-topics --create --topic demo-kafka --partitions 2 --replication-factor 1 --if-not-exists  --bootstrap-server kafka:19092 '"]
  script:
    - cd quarkus-kafka
    - echo "Compiling the code..."
    - 'mvn $MAVEN_CLI_OPTS verify'
